### ISSUE TITLE
Code services have invalid paths to dependencies

### ISSUE THREAD

**Issue by savfaire** [ClearBlade/asset-monitor#2]
When building code services using cb-dev-kit, compilation errors occur because of invalid locations in the import statements.

normalizerUsingLibSS
ERROR in ./src/code/services/normalizerNimbelinkSS/normalizerNimbelinkSS.ts
Module not found: Error: Can't resolve '@clearblade/asset-monitor/lib/backend/promise-polyfill/index.js' in '/Users/jim/Documents/ClearBlade/SolutionsAndServices/Services/Projects/TTX/assetmonitor-ttx/src/code/services/normalizerNimbelinkSS'
 @ ./src/code/services/normalizerNimbelinkSS/normalizerNimbelinkSS.ts 10:0-73

createAssetHistorySS.ts
ERROR in ./src/code/services/createAssetHistorySS/createAssetHistorySS.ts
Module not found: Error: Can't resolve '@clearblade/asset-monitor/lib/backend/collection-lib' in '/Users/jim/Documents/ClearBlade/SolutionsAndServices/Services/Projects/TTX/assetmonitor-ttx/src/code/services/createAssetHistorySS'
 @ ./src/code/services/createAssetHistorySS/createAssetHistorySS.ts 2:0-87 63:27-42 122:24-39

updateAssetLocationSS
ERROR in ./src/code/services/updateAssetLocationSS/updateAssetLocationSS.ts
Module not found: Error: Can't resolve '@clearblade/asset-monitor/lib/backend/collection-lib' in '/Users/jim/Documents/ClearBlade/SolutionsAndServices/Services/Projects/TTX/assetmonitor-ttx/src/code/services/updateAssetLocationSS'
 @ ./src/code/services/updateAssetLocationSS/updateAssetLocationSS.ts 2:0-87 65:20-35 94:20-35 126:20-35

updateAssetStatusSS
ERROR in ./src/code/services/updateAssetStatusSS/updateAssetStatusSS.ts
Module not found: Error: Can't resolve '@clearblade/asset-monitor/lib/backend/collection-lib' in '/Users/jim/Documents/ClearBlade/SolutionsAndServices/Services/Projects/TTX/assetmonitor-ttx/src/code/services/updateAssetStatusSS'
 @ ./src/code/services/updateAssetStatusSS/updateAssetStatusSS.ts 2:0-87 59:20-35 73:20-35

updateAssetLocationSS
ERROR in ./src/code/services/updateAssetLocationSS/updateAssetLocationSS.ts
Module not found: Error: Can't resolve '@clearblade/asset-monitor/lib/backend/collection-lib' in '/Users/jim/Documents/ClearBlade/SolutionsAndServices/Services/Projects/TTX/assetmonitor-ttx/src/code/services/updateAssetLocationSS'
 @ ./src/code/services/updateAssetLocationSS/updateAssetLocationSS.ts 2:0-87 65:20-35 94:20-35 126:20-35

I modified the services and added relative paths because the unresolved items are not in the npm package. These items need to be added to the npm package if the paths in the import statements are to remain unchaned.

**Comment by sh3nan1gans** [comment]
@savfaire - I think this is no longer an issue. Please reopen if necessary
